# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iget' do
  # Pods for iget
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'
  # pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'
  # pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  # pod 'react-native-gps-state', :path => '../node_modules/react-native-gps-state'
  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'
  # pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
